// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyCZNsYzBXkdkadnnt7b-5bbuKC2pLIz0OM',
    appId: '1:1044097755143:web:35cf3aac78368d0c0fe2a2',
    messagingSenderId: '1044097755143',
    projectId: 'hear-my-door-l',
    authDomain: 'hear-my-door-l.firebaseapp.com',
    storageBucket: 'hear-my-door-l.firebasestorage.app',
    measurementId: 'G-LDR69717PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJs_v5aiSwNw0_4KcTnOa2wErssUTi88',
    appId: '1:1044097755143:android:8d6b24056161ac260fe2a2',
    messagingSenderId: '1044097755143',
    projectId: 'hear-my-door-l',
    storageBucket: 'hear-my-door-l.firebasestorage.app',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDaQPUkJMXbwwgGMLfG7xyATmbP3tlAAzw',
    appId: '1:1044097755143:ios:60bcc466f86e6d9c0fe2a2',
    messagingSenderId: '1044097755143',
    projectId: 'hear-my-door-l',
    storageBucket: 'hear-my-door-l.firebasestorage.app',
    iosBundleId: 'com.example.quickMedical',
  );
}
